### ISSUE TITLE
No License by intent

### ISSUE THREAD

**Issue by fin0** [asdfjkl/pgn2anki#4]
Hey Dominik,

I enjoy the project and maybe would like to build some more features upon it. But I realized, that you did not include a license. As far as I understand it, nobody is permitted to build upon the source code in this case:
https://opensource.stackexchange.com/a/1721
https://choosealicense.com/no-permission/

If there is no license by accident, I would kindly ask you to add it :) If this is by purpose, nevermind, just close this issue. To make it clear, I don't want to push you to give permissions away, just wanted to ask if this is by purpose or not! Thanks for the work and have a nice day!

**Comment by asdfjkl** [comment]
added missing license information (GPL 3)
